#!/bin/sh
set -eux

if [ -f ${SRC_PKG}/requirements.txt ]
then 
    pip3 install -i https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple -r ${SRC_PKG}/requirements.txt -t ${SRC_PKG} 
fi
cp -r ${SRC_PKG} ${DEPLOY_PKG}
